### ISSUE TITLE
Improve scope of this project by providing datasets

### ISSUE THREAD

**Issue by dhananjaypai08** [CMPN-CODECELL/Netflix-Data-Cleaning-Analysis-and-Visualization#3]
Require more Datasets(preferably csv files)
These datasets will help for using data cleaning and analyzing techniques on various other datasets which will help in good understanding
**NOTE: Only the assigned contributors PR will be merged to prevent from spamming as this is an easy task**

**Comment by SammriddhGupta** [comment]
Can I be assigned this issue

**Comment by Adityaa-15** [comment]
Please assign me this issue

**Comment by dhananjaypai08** [comment]
> Please assign me this issue

Hi, this issue has been assigned. You can work on some other issues if you want
